### ISSUE TITLE
Factory inject

### ISSUE THREAD

**Issue by xam8re** [damirkusar/leptir-generator#1]
If i add a service with yo leptir-angular-bootstrap:service newService, i cant inject into my controller.

**Comment by damirkusar** [comment]
Hi @xam8re,

sorry for the late response. Don't know where your problem is. What and how are you including it? I tested it and it works perfectly fine. Created a new Service and added it in demo controller. 

My Service

```
'use strict';
angular.module('demo').factory('NewServiceService', [function () {
    return {
        getDummyText: function(){
            return 'dummyText issue';
        }
    };
}]);
```

My Controller

```
'use strict';
angular.module('demo')
    .controller('DemoCtrl', ['$scope', 'NewServiceService', function($scope, NewServiceService){
        $scope.ModuleTest = "Modify me in demo Module: " + NewServiceService.getDummyText();
}]);
```

And this works perfectly fine.
